---
title: "Data Inventory"
---

```{r}
#| echo: false
#| message: false
library(here)
source(here("analysis", "R", "load_data.R"))
source(here("analysis", "R", "plots.R"))
```

## Overview

This analysis visualizes Chinese development projects around the world using data from AidData's China's Global Loans and Grants Dataset, Version 1.0.

## Temporal Trends (2000-2023)

```{r}
create_temporal_trends(clg_dev) |>
  config(
    modeBarButtonsToRemove = c("zoom2d", "pan2d", "select2d", "lasso2d",
                               "zoomIn2d", "zoomOut2d", "autoScale2d",
                               "resetScale2d", "toImage"),
    displaylogo = FALSE,
    scrollZoom  = FALSE
  )
```

## Geographic Distribution of Projects

:::panel-tabset

### Total Projects
```{r}
create_flat_map_visualization(
  clg_dev,
  agg_col     = "AidData_Record_ID",
  agg_func    = "nunique",
  value_label = "Number of Projects",
  color_scale = "YlOrRd",
  format_fn   = function(x) as.character(as.integer(x))
) |>
  config(
    modeBarButtonsToRemove = c("lasso2d", "select2d", "resetGeo", "toImage"),
    displaylogo = FALSE,
    responsive  = TRUE
  )
```

### Total Funding (USD)
```{r}
# 10 discrete percentile categories; Pakistan annotated as outlier
create_flat_map_visualization(
  clg_dev,
  agg_col           = "Amount_Constant_USD_2023",
  agg_func          = "sum",
  value_label       = "Total USD (2023)",
  zmax              = 10e9,
  use_percentiles   = TRUE,
  outlier_color     = "rgb(20, 0, 50)",
  outlier_countries = list(Pakistan = c(30.3752, 69.3451))
) |>
  config(
    modeBarButtonsToRemove = c("lasso2d", "select2d", "resetGeo", "toImage"),
    displaylogo = FALSE,
    responsive  = TRUE
  )
```

:::
